# Generated by Django 3.1.3 on 2021-02-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='category',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.AddField(
            model_name='workout',
            name='jtype',
            field=models.JSONField(default=[]),
        ),
    ]
