# Generated by Django 3.1.3 on 2021-02-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20210206_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='jtype',
            new_name='exercises',
        ),
    ]
